### ISSUE TITLE
Error running ebowla

### ISSUE THREAD

**Issue by cjconstante** [Genetic-Malware/Ebowla#10]
Hi guys. I have cloned the repository and installed the dependencies as in the guide. But, when i try to run ./ebowla.py i got this error:
[x] Error - You need to have configobj installed to use this tool

I have installed on my Ubuntu 16 LTS this before:
- sudo aptitude install python-configobj
- sudo -H pip install configobj

I can see the configobj is installed but i got the mentioned error.

Thanks.

**Comment by secretsquirrel** [comment]
Ubuntu 16 LTS comes python3 as default.

Ebowla uses python2.

I forced ./ebowla.py to use python2, though you may still need to install it (git pull).

I can't help you with your working distro though.

**Comment by cjconstante** [comment]
Which specific kali version it works? I have tried with kali 2106.2 and get the same error.

**Comment by secretsquirrel** [comment]
If you do the following what do you see?

```
$python
>>> import configobj

```

**Comment by cjconstante** [comment]
This i get:

python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> help
Type help() for interactive help, or help(object) for help about object.
>>> import configobj
>>>

**Comment by secretsquirrel** [comment]
Hm.  I don't know what to tell you.  Good luck!

**Comment by cjconstante** [comment]
Hi again, i don't give up!

I just installed configobj from virtualenv i passed the previous error and now i get this:

Traceback (most recent call last):
  File "./ebowla.py", line 10, in <module>
    from encryption import otp_full
  File "/root/Ebowla/encryption/otp_full.py", line 11, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher


How can help me with this?

Thanks.

**Comment by cjconstante** [comment]
I just think there is only one step to run properly. Now i get this:

[*] Payload length: 0x2dc7af
[*] Payload_type exe
[*] Using EXE payload template
[*] Using the following as an OTP: pads/BitTorrent.exe
[*] Using a maximum pad size of: 0xffffff
Traceback (most recent call last):
  File "./ebowla.py", line 75, in <module>
    test = make_payload(sys.argv[1], sys.argv[2])
  File "./ebowla.py", line 24, in __init__
    self.main()
  File "./ebowla.py", line 43, in main
    otp_full.otp_full(pad, self.payload, byte_width, otp_type, payload_type, minus_bytes, scan_dir, output_type, pad_max,clean_output)
  File "/root/Ebowla/encryption/otp_full.py", line 53, in __init__
    with open(pad, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'pads/BitTorrent.exe'

**Comment by JohnTroony** [comment]
Honestly, looks like your setup is fkd up. 
`No such file or directory: 'pads/BitTorrent.exe'`

```
Presentation Resources

Slides:

https://github.com/Genetic-Malware/Ebowla/raw/master/Infiltrate_2016_Morrow_Pitts_Genetic_Malware.pdf

Demos

Demo1: https://www.youtube.com/watch?v=rRm3O7w5GHg

Demo2: https://youtu.be/Bu_qDrbX9Zo

Demo3: https://youtu.be/mlh70LtwmDo
```

**Comment by cjconstante** [comment]
I RTFM and i don't get this point:

IOError: [Errno 2] No such file or directory: 'pads/BitTorrent.exe'

This must be a file/path in my attacking or victim machine? it can be any exe file or other format? Where it must be located?
