### ISSUE TITLE
A couple os issues running powershell payload

### ISSUE THREAD

**Issue by ubermanchego** [Genetic-Malware/Ebowla#17]
Hi there,
I'm testing you tool and loving it, but when running Ebowla with the powershell payload(Empire launcher) I got a couple of errors.
When I try the generated ps1 script in the victim machine(Windows 10), I get the following error message every time:
![captura de pantalla 2017-03-19 a las 21 05 47](https://cloud.githubusercontent.com/assets/6847856/24084302/e54a1ee8-0ce7-11e7-9826-a41d4269d3fd.png)

Although I get the agent back all the same:

![captura de pantalla 2017-03-19 a las 21 09 33](https://cloud.githubusercontent.com/assets/6847856/24084327/70cc6750-0ce8-11e7-9218-1b3dc995dfd2.png)

The other issue is when I try to set the clean_output to True, with the same payload, I get this error:

**[*] Writing Powershell payload to: powershell_symmetric_launcher1.ps1.ps1
[!] Error Selecting Type of File for Cleaning : powershell_symmetric_launcher1.ps1.ps1**

Running the script still gives me all the output, and the same error as before.
I uploaded my config file to pastebin if it's of any help: https://pastebin.com/SvK7vBbE

**Comment by secretsquirrel** [comment]
You are running your own provided code from what I can tell. 

The error lies there.

There is no cleaning for powershell scripts yet.

**Comment by ubermanchego** [comment]
It's the powershell launcher code straight from Empire 2.0.

**Comment by secretsquirrel** [comment]
👍
