### ISSUE TITLE
TypeError: Unknown parameters for CBC

### ISSUE THREAD

**Issue by ankushgoel27** [Genetic-Malware/Ebowla#21]
Hi,

I am getting this error when i run this tool on kali linux. Below are the exact logs. Am i running it incorreclty?

./ebowla.py ../Empire/stager.ps1 genetic.config
[*] Using Symmetric encryption
[*] Payload length 1313
[*] Payload_type code
[*] Used environment variables:
	[-] environment value used: userdomain, value used: desktop-e1d6g0a
	[-] environment value used: username, value used: admin
[!] Path string not used as pasrt of key
[!] External IP mask NOT used as part of key
[!] System time mask NOT used as part of key
[*] String used to source the encryption key: desktop-e1d6g0aadmin
[*] Applying 10000 sha512 hash iterations before encryption
[*] Encryption key: 84bc9df8971be29fd3b16b82ceef34547d47ef270edf0223f44a1844a742e9a4
Traceback (most recent call last):
  File "./ebowla.py", line 75, in <module>
    test = make_payload(sys.argv[1], sys.argv[2])
  File "./ebowla.py", line 24, in __init__
    self.main()
  File "./ebowla.py", line 66, in main
    env.env_encrypt(key_config, self.payload, payload_type, minus_bytes, output_type, key_iterations, clean_output)
  File "/opt/Ebowla/encryption/env.py", line 76, in __init__
    self.find_key_encrypt()
  File "/opt/Ebowla/encryption/env.py", line 282, in find_key_encrypt
    segment_size = ps_block_size,
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 264, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/__init__.py", line 130, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/_mode_cbc.py", line 245, in _create_cbc_cipher
    raise TypeError("Unknown parameters for CBC: %s" % str(kwargs))
TypeError: Unknown parameters for CBC: {'segment_size': 128}

**Comment by secretsquirrel** [comment]
I think you are using python-cryptograhy vs pycrypto. Use pycrypto.

`pip install pycrypto`

```
$ ./ebowla.py meterpreter_x64_172.16.186.1.exe genetic.config
[*] Using Symmetric encryption
[*] Payload length 7168
[*] Payload_type code
[*] Used environment variables:
	[-] environment value used: username, value used: admin
[!] Path string not used as pasrt of key
[!] External IP mask NOT used as part of key
[*] System time mask used as part of key: 20161200
[*] String used to source the encryption key: admin20161200
[*] Applying 10000 sha512 hash iterations before encryption
[*] Encryption key: 8749304fcfead05608d54ce12506717164fdcc90ba553ef85c3a3f9dc23610e7
[*] Length of encrypted payload 7168 and hash: 8b495f8622e65f1b051cb296d9550e69709875006aad102504c930dd3d5c80d80edc8e2ae0120c78a0895b2fc4fa0f58095c8fbe6d6721cadf2da94b17da6c6a
[*] Payload hash (minus_bytes): cab57730e1fc6b546d9afb2cba90d20239585f2ac73dd896785fafad9218b2d996bc6d4ad9b56c2b9e93fed76a037dd38dc3f4fe2575fb2db5cf0da86bdf2327
[*] Hash of full payload: c375f2a3dfb911773f10363270a839a30f676f767dcc3fc95d48e9c45a9f4edd3d5b3a3417c1fc294fa6664fbde0db29e846b50ac6494c24534696c35ef001dd
[*] Writing Python payload to: python_symmetric_meterpreter_x64_172.16.186.1.exe.py
$ pip show pycrypto                                         
Name: pycrypto
Version: 2.6.1
Summary: Cryptographic modules for Python.
Home-page: http://www.pycrypto.org/
Author: Dwayne C. Litzenberger
Author-email: dlitz@dlitz.net
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages
Requires: 
```
