### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by webkodex** [Genetic-Malware/Ebowla#24]
# go version
go version go1.10.3 linux/amd64

root@kali:/opt/Ebowla# ./build_x64_go.sh output/go_symmetric_shell-9004.exe.go ebowla-shell-9004.exe
[*] Copy Files to tmp for building
[*] Building...
# runtime/cgo
exec: "x86_64-w64-mingw32-gcc": executable file not found in $PATH
[*] Building complete
[*] Copy ebowla-shell-9004.exe to output
cp: cannot stat '/tmp/ebowla-shell-9004.exe': No such file or directory
[*] Cleaning up
rm: cannot remove '/tmp/ebowla-shell-9004.exe': No such file or directory
[*] Done

please suggest how to fix this error ?

Regards
skorpinok

**Comment by secretsquirrel** [comment]
See this: https://github.com/Genetic-Malware/Ebowla#known-issues

**Comment by webkodex** [comment]
I have seen that several times, if you think I should downgrade to another version then kindly suggest me how to do that, just don't redirect me to some blind spot where I can't see anything. When you create a tool.. make sure you got right vaccine to cure any infection.

**Comment by secretsquirrel** [comment]
It's free software with no support. Feel free to use something else.
