### ISSUE TITLE
KeyError: 'Overall'

### ISSUE THREAD

**Issue by lgcambero** [Genetic-Malware/Ebowla#7]
Hello, I could help with this error? Thank you.
![error](https://cloud.githubusercontent.com/assets/11602705/15623676/712a3062-244d-11e6-946f-eb463c0f3fc5.jpg)

**Comment by secretsquirrel** [comment]
Can you throw your config on pastebin and reply with the link to it?

**Comment by secretsquirrel** [comment]
It seems you are calling config instead of genetic.conifg. I don't see 'config' in the directory.

**Comment by lgcambero** [comment]
Sorry I did not realize, how or where to meterpreter_reverse generate dll?

**Comment by secretsquirrel** [comment]
Try this:
https://github.com/rapid7/metasploit-framework/wiki/How-to-use-msfvenom

On Fri, May 27, 2016 at 8:56 PM, lgcambero <notifications@github.com> wrote:

> Sorry I did not realize, how or where to meterpreter_reverse generate dll?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Genetic-Malware/Ebowla/issues/7#issuecomment-222281281>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABmh6iZswfZTjvVe2qnLiftDsTGpCCtxks5qF5KjgaJpZM4Io8Y7>
> .
>



-- 
Josh
703.507.4468
