### ISSUE TITLE
illegal rune literal

### ISSUE THREAD

**Issue by evilgash** [Genetic-Malware/Ebowla#8]
when I use go with ENV and try to compile with ./build_x64_go.sh I get the following error:

# command-line-arguments
./demo-go.go:130:21: illegal rune literal

I checked the file and found the following in  ./templates/go/go_env_base.py:        fmt.Println('==================================================')

I changed this to:
fmt.Println("==================================================")

and now at least it compiles ;)

**Comment by secretsquirrel** [comment]
thanks, fixed!
